[dependencies]
ic-vetkeys = "0.3.0"
core = "1.0.0"
vector = "0.4.2"
map = "9.0.1"
memory-region = "1.3.2"
sha2 = "0.1.6"
tid = "1.1.0"
ic = "3.2.0"
certified-assets = "0.6.0"
liminal = "1.3.0"
url-kit = "3.0.0"

[package]
name = "encrypted-storage"
version = "0.1.0"
