[dependencies]
ic-vetkeys = "0.4.0"
vector = "0.4.2"
map = "9.0.1"
memory-region = "1.3.2"
sha2 = "0.1.9"
tid = "1.1.0"
ic = "3.2.0"
certified-assets = "0.6.0"
liminal = "3.1.0"
url-kit = "4.0.1"
base-x-encoder = "2.1.0"
xtended-numbers = "2.1.0"
candid = "2.1.0"
core = "https://github.com/dfinity/motoko-core#moc-1.0.0"

[package]
name = "encrypted-storage"
version = "0.1.0"

[toolchain]
moc = "1.0.0-nullc-2"
