[dependencies]
map = "9.0.1"
certified-assets = "0.5.1"
moh = "https://github.com/NatLabs/moh#main@27f9634adf5b3b85bcf8bfa381875d82395e464c"
ic = "2.1.0"
core = "0.5.0"
vector = "0.4.2"

[dev-dependencies]
test = "2.1.1"
