[dependencies]
memory-region = "1.3.2"
base = "0.16.0"
map = "9.0.1"
ic = "3.2.0"
ic-vetkeys = "0.4.0"
encrypted-storage = "../encrypted-storage-mo"
certified-assets = "0.6.0"
base-x-encoder = "2.1.0"
liminal = "3.1.0"
http-assets = "0.2.0"
zendb = "0.1.0"
json = "1.4.0"
compression = "0.3.0"
sha2 = "0.1.9"
hex = "1.0.2"
core = "https://github.com/dfinity/motoko-core#moc-1.0.0"
datetime = "1.1.0"
tar = "https://github.com/christoph-dfinity/motoko-tar#9dcd0bd79fe26a81cdfa75b5c8104c68a4cd67d9"
vector = "0.4.3"
xtended-numbers = "2.3.0"
candid = "2.4.2"
byte-utils = "0.1.1"

[toolchain]
moc = "1.0.0-nullc-2"
wasmtime = "39.0.1"
