[dependencies]
base = "0.16.0"
map = "9.0.1"
ic = "3.2.0"
ic-vetkeys = "0.3.0"
encrypted-storage = "../encrypted-storage-mo"
certified-assets = "0.6.0"
base-x-encoder = "2.1.0"
xtended-numbers = "2.1.0"
candid = "2.1.0"
liminal = "1.3.0"
http-assets = "0.2.0"
